### ISSUE TITLE
Duplicate packages after merge

### ISSUE THREAD

**Issue by vargenau** [interlynk-io/sbomasm#101]
[example6-src.spdx.txt](https://github.com/user-attachments/files/16850443/example6-src.spdx.txt)
[example6-lib.spdx.txt](https://github.com/user-attachments/files/16850444/example6-lib.spdx.txt)
[merge.spdx.json](https://github.com/user-attachments/files/16850448/merge.spdx.json)

```
sbomasm assemble -n merge -v 1 -t "application" -o merge.spdx.json example6-*.spdx 
```
Both `example6-src.spdx` and `example6-lib.spdx` contain identical packages, `go.reflect` and `go.strconv`.

In the merge, these packages are present twice.

I would expect no duplicates.

In real-world examples, I have many duplicates.

**Comment by viveksahu26** [comment]
Thanks for raising this issue. Will get back to you :+1:

**Comment by riteshnoronha** [comment]
@vargenau yes as mentioned in our readme, we do not remove duplicates, but if that is a requirement we will need to add a mode to each merge algo to remove duplicate components. 

A potential Algo to identify duplicates would be
1. PURL match 
2. CPE match 
3. Name-Version match 
4. Checksum match
We would execute these checks in a sequence, whichever matches indicates its a duplicate and eleminate it. 

Thanks for a feature request will work on this.

**Comment by vargenau** [comment]
Any progress on implementing this?

**Comment by riteshnoronha** [comment]
@vargenau we implemented this for CycloneDX, will move over the logic for SPDX by next release.

**Comment by vargenau** [comment]
Very good, thank you!

**Comment by riteshnoronha** [comment]
@vargenau v0.2.0 has been released please give it a shot.

**Comment by vargenau** [comment]
> @vargenau v0.2.0 has been released please give it a shot.

Yes, I have seen it. I will check. Thank you for the improvement.
