### ISSUE TITLE
`sbomasm` should probably add itself as a tool

### ISSUE THREAD

**Issue by vpetersson** [interlynk-io/sbomasm#115]
@riteshnoronha You're already aware of this as you crafted the [PR](https://github.com/CISA-SBOM-Community/SBOM-Generation/pull/52/files) that resolved this, but it would probably make sense for `sbomasm` to append itself under the tools section.

**Comment by riteshnoronha** [comment]
Yes. I'm working on the auto-annotation feature, will add it as a part of it.

**Comment by riteshnoronha** [comment]
@vpetersson  should be fixed now in v0.2.0.
