### ISSUE TITLE
sbomasm creates invalid SPDX

### ISSUE THREAD

**Issue by vargenau** [interlynk-io/sbomasm#56]
Get the 3 SPDX files from https://github.com/spdx/spdx-examples/tree/master/software/example6/spdx2.2

These 3 files are valid SPDX.

Do:
```
sbomasm assemble -n merge -v 1 -t application -o merge.spdx.json *.spdx
```

Result is invalid SPDX:
```
pyspdxtools -i merge.spdx.json 
ERROR:root:The document is invalid. The following issues have been found:
document_ref_id must only contain letters, numbers, ".", "-" and "+" and must begin with "DocumentRef-", but is: hello-go-src
document_ref_id must only contain letters, numbers, ".", "-" and "+" and must begin with "DocumentRef-", but is: go-lib
verification_code must be None if files_analyzed is False, but is: PackageVerificationCode(value='', excluded_files=[])
verification_code must be None if files_analyzed is False, but is: PackageVerificationCode(value='', excluded_files=[])
verification_code must be None if files_analyzed is False, but is: PackageVerificationCode(value='', excluded_files=[])
verification_code must be None if files_analyzed is False, but is: PackageVerificationCode(value='', excluded_files=[])
verification_code must be None if files_analyzed is False, but is: PackageVerificationCode(value='', excluded_files=[])
did not find the referenced spdx_id "SPDXRef-hello-go-binary" in the SPDX document
did not find the external document reference "DocumentRef-hello-go-src" in the SPDX document
did not find the referenced spdx_id "SPDXRef-hello-go-binary" in the SPDX document
did not find the external document reference "DocumentRef-hello-go-src" in the SPDX document
did not find the external document reference "DocumentRef-go-lib" in the SPDX document
did not find the external document reference "DocumentRef-go-lib" in the SPDX document
did not find the external document reference "DocumentRef-go-lib" in the SPDX document
did not find the external document reference "DocumentRef-go-lib" in the SPDX document
did not find the external document reference "DocumentRef-go-lib" in the SPDX document
did not find the referenced spdx_id "SPDXRef-Makefile" in the SPDX document
```

**Comment by riteshnoronha** [comment]
@vargenau thanks for reporting, let me check and get back to u

**Comment by riteshnoronha** [comment]
Thanks @vargenau  for reporting this issue. Looks like i had not considered many cases during the merge. Here is a summary of all the changes made 

1. Include creators(Tool/Person/Org) from all sboms in the merge-set into the output sbom.
2. Remove external references of documents which are part of the merge-set.
3. Remove docref from relationships which are part of the merge-set. 
4. SPDX2.2 has the concept of files within a package, that is not true for SPDX2.3. 
5. pyspdxtool reports an error if filesAnalyzed is set to false, then no relationships can exist. My read on the spec does not align with this. I have left my code as is.

For now if you run your command again, with the new release 0.1.1, you will get a merged spdx 2.3 document. However it will still not pass pyspdxtool, as the input file https://github.com/spdx/spdx-examples/blob/master/software/example6/spdx2.2/example6-lib.spdx also fails. The claim is that if a package contains FilesAnalyzed as false, it cannot have relationships, as you can see the original file has it. In the merge i could have filtered it out, but when i read the spec, it not clear if that is the intention. 


Again thanks for using the tool, and if you have any more issues do let me know. 

-Ritesh

**Comment by vargenau** [comment]
Hello @riteshnoronha ,

Thank you very much for the quick fixes.
I have tested with release 0.1.2 and the result is fully valid according to pyspdxtool

However, the Java tools https://github.com/spdx/tools-java say it is invalid and I think they are right.
```
This SPDX Document is not valid due to:
	Duplicate extracted license ID: LicenseRef-Golang-BSD-plus-Patents
```
You have the same License-Ref- coming from two different files ```example6-bin.spdx``` and ```example6-lib.spdx```
You should probably probably handle this case:
- by outputting the License-Ref- only once if the content is the same
- by creating a new identifier if the content is different

**Comment by vargenau** [comment]
One more remark.
The input files do no contain a LicenseListVersion
In the merge, you get one with value 3.19
Why this value? It should probably be present in the merge as not present in the input.

**Comment by riteshnoronha** [comment]
@vargenau thanks for the feedback,  i have fixed both of these issues as described here https://github.com/interlynk-io/sbomasm/pull/72

The only thing pending is 
`by creating a new identifier if the content is different` 

I have a feeling this would be an edge case, but will keep and eye out for it. Unless u have some sboms exhibiting this behaviour.

**Comment by riteshnoronha** [comment]
Will make a release by the end of the week with these changes.

**Comment by riteshnoronha** [comment]
@vargenau ok version v0.1.3 has been released. We also publish the SBOM & VEX for sbomasm at https://github.com/interlynk-io/sbomasm?tab=readme-ov-file#sbom-card , if you click on it, it takes you to all the versions, its sboms and vex in the vulns tab. 


As always thanks for using the tool, and let me know if you have any more feedback.

**Comment by vargenau** [comment]
@riteshnoronha With Homebrew, it still installs v0.1.2. Do you have something to do or should I just wait?

**Comment by surendrapathak** [comment]
@vargenau We missed upgrading the formula. I just pushed that here : https://github.com/interlynk-io/homebrew-interlynk/pull/67 .. Can you retry?

**Comment by vargenau** [comment]
Yes, it works now with Homebrew. Thank you.

I had downloaded the binary by hand. More issues to come. :-)
