### ISSUE TITLE
LicenseListVersion creates invalid SPDX

### ISSUE THREAD

**Issue by vargenau** [interlynk-io/sbomasm#67]
[example6-src.spdx.txt](https://github.com/user-attachments/files/16131131/example6-src.spdx.txt)
[example6-lib.spdx.txt](https://github.com/user-attachments/files/16131132/example6-lib.spdx.txt)
[example6-bin.spdx.txt](https://github.com/user-attachments/files/16131133/example6-bin.spdx.txt)

```
sbomasm assemble -n merge -v 1 -t application -o merge.spdx.json *.spdx

```
Result:
[merge.spdx.json](https://github.com/user-attachments/files/16131143/merge.spdx.json)

```
pyspdxtools -i merge.spdx.json 
ERROR:root:There have been issues while parsing the provided document:
Error while parsing Document: ['Error while parsing version 3.18.0: 3.18.0 is not a valid version string']
```

Also, there should be strategy to select the LicenseListVersion in case of different values in the input files.
I think the best strategy is to take the highest value (a lower value would not be good, possibly some used identifiers would not be present in the list).

**Comment by riteshnoronha** [comment]
Good point. Have a fix for this https://github.com/interlynk-io/sbomasm/pull/70
