### ISSUE TITLE
sbomasm does not work without internet connection

### ISSUE THREAD

**Issue by vargenau** [interlynk-io/sbomasm#68]
Without internet connect, I get:
```
sbomasm assemble -n merge -v 1 -t application -o merge.spdx.json *.spdx
panic: Get "https://api.github.com/repos/interlynk-io/sbomasm/releases/latest": proxyconnect tcp: dial tcp xxx.xxxx.xxx.xxx:8000: connect: network is unreachable

goroutine 1 [running]:
github.com/interlynk-io/sbomasm/cmd.checkIfLatestRelease()
	github.com/interlynk-io/sbomasm@v0.1.2/cmd/root.go:71 +0x1b8
github.com/interlynk-io/sbomasm/cmd.Execute()
	github.com/interlynk-io/sbomasm@v0.1.2/cmd/root.go:43 +0x1c
main.main()
	github.com/interlynk-io/sbomasm@v0.1.2/main.go:19 +0x1c
```
Why does sbomasm need internet connection? Only to check if we have the latest release?
Is the content of the input files sent to Interlynk? That would cause confidentiality issues.

**Comment by riteshnoronha** [comment]
@vargenau  we take privacy very seriously. I can say with certainty that no data is sent to interlynk or anywhere else. Yes we use github releases to check for latest version, you can disable it using this `INTERLYNK_DISABLE_VERSION_CHECK=true`.

Also just realized we have not documented this for sbomasm. Will add that. 

https://github.com/interlynk-io/sbomqs?tab=readme-ov-file#quality-score-in-an-airgapped-environment

**Comment by riteshnoronha** [comment]
https://github.com/interlynk-io/sbomasm/pull/69

**Comment by vargenau** [comment]
Thank you @riteshnoronha for your quick answer!
