### ISSUE TITLE
"primaryPackagePurpose": "application" is invalid

### ISSUE THREAD

**Issue by vargenau** [interlynk-io/sbomasm#73]
[merge.spdx.json](https://github.com/user-attachments/files/16157762/merge.spdx.json)

`"primaryPackagePurpose": "application"` is invalid, it should be `"primaryPackagePurpose": "APPLICATION"`

See https://github.com/spdx/tools-python/issues/812

But this is an optional attribute, I would drop it. It was not present in the original files, so I cannot see how you can deduce it.

**Comment by vargenau** [comment]
v0.1.3

**Comment by vargenau** [comment]
The merge was done with:
```
sbomasm assemble -n merge -v 1 -t application -o merge.spdx.json *.spdx
```
So the `primaryPackagePurpose`comes from the `-t` option.

You allow: application, framework, library, container, device, firmware

This should be translated as: APPLICATION, FRAMEWORK, LIBRARY,  CONTAINER , DEVICE, FIRMWARE

**Comment by riteshnoronha** [comment]
Yup, yeah i just read the spec its all caps. 😭  will make the change.

**Comment by riteshnoronha** [comment]
Ok fixed with https://github.com/interlynk-io/sbomasm/pull/79 now u will get a warning if it does not match what SPDX requires it to be.  And if correct, the value will be capitalized.
