### ISSUE TITLE
sbomasm should refuse to merge a single file

### ISSUE THREAD

**Issue by vargenau** [interlynk-io/sbomasm#74]
If you provide a single input file, sbomasm will create a new file that is more complex than the original file as it will contain one more package "merge".

I do not see the purpose of this.

sbomasm should refuse to merge a single file.

**Comment by riteshnoronha** [comment]
True

**Comment by riteshnoronha** [comment]
Fixed with https://github.com/interlynk-io/sbomasm/pull/80
