### ISSUE TITLE
duplicate spdx_id

### ISSUE THREAD

**Issue by vargenau** [interlynk-io/sbomasm#76]
It is possible that different files contain the same package.

This is a toy example, but in real SBOMs (that I cannot provide for confidentiality reasons), it happens often.

You should create different `spdx_id`s, or create a single instance of the package if it is exactly the same in both files.

[duplicate1.spdx.txt](https://github.com/user-attachments/files/16159274/duplicate1.spdx.txt)
[duplicate2.spdx.txt](https://github.com/user-attachments/files/16159282/duplicate2.spdx.txt)

```
sbomasm assemble -n merge -v 1 -t application -o merge.spdx.json *.spdx
```

[merge.spdx.json](https://github.com/user-attachments/files/16159284/merge.spdx.json)

```
pyspdxtools -i merge.spdx.json 
ERROR:root:The document is invalid. The following issues have been found:
every spdx_id must be unique within the document, but found the following duplicates: ['SPDXRef-Package-crypto-js']
```

**Comment by riteshnoronha** [comment]
Yes i had this implemented for cyclonedx but never ported it over the SPDX. Thanks for calling it out. fixed here https://github.com/interlynk-io/sbomasm/pull/84

**Comment by riteshnoronha** [comment]
v0.1.4 has been released with this fix.

**Comment by vargenau** [comment]
@riteshnoronha 
Thank you very much.
I now get fully valid SPDX on my real-world example.

**Comment by riteshnoronha** [comment]
@vargenau great to hear. 👍
