### ISSUE TITLE
missing referenced spdx_id in merge

### ISSUE THREAD

**Issue by vargenau** [interlynk-io/sbomasm#77]
[main.spdx.txt](https://github.com/user-attachments/files/16159683/main.spdx.txt)
[other.spdx.txt](https://github.com/user-attachments/files/16159682/other.spdx.txt)

```
sbomasm assemble -n merge -v 1 -t application -o merge.spdx.json *.spdx
```

[merge.spdx.json](https://github.com/user-attachments/files/16159684/merge.spdx.json)

```
pyspdxtools -i merge.spdx.json 
ERROR:root:The document is invalid. The following issues have been found:
did not find the referenced spdx_id "SPDXRef-Package-other" in the SPDX document
did not find the referenced spdx_id "SPDXRef-Package-other" in the SPDX document
```

**Comment by viveksahu26** [comment]
Hey @vargenau . Thanks for raising an issue.  Wanted to know the o/p of the below command:
`pyspdxtools -i main.spdx.txt` and `pyspdxtools -i other.spdx.txt`

**Comment by vargenau** [comment]
Both files are valid SPDX.
```
pyspdxtools -i main.spdx
pyspdxtools -i other.spdx
```
give no result, meaning they are valid.

The Java Tools also say files are valid SPDX.

I had to rename the files by adding `.txt` in order to be able to upload them on GitHub. You should rename them back to do the tests.

I always provide valid SPDX as input in my issues.

**Comment by riteshnoronha** [comment]
fixed here https://github.com/interlynk-io/sbomasm/pull/84

**Comment by riteshnoronha** [comment]
v0.1.4 has been released with this fix.
